id: 2a2ffce2740446149baec7d74bd96175
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN833
  title: སྤྱི་ལོ ༢༠༠༩་ལོར་ནོར་བུ་སོགས་ཀྱིས་ཉར་ཚགས་བྱས་པའི་སྡེ་དགེའི་དམངས་ཁྲོད་ཀྱི་གནའ་དཔེ་བྲིས་མའི་གློག་རྡུལ་འདྲ་བཤུས།
  volumes:
    8fa96371f5a6437f9cc96441cf917957:
      image_group_id: I2KG229635
      title: ''
      base_file: v001.txt
  author: ''
